/* automatically generated by rust-bindgen 0.69.1 */

pub const DOMAIN: u32 = 1;
pub const SING: u32 = 2;
pub const OVERFLOW: u32 = 3;
pub const UNDERFLOW: u32 = 4;
pub const TLOSS: u32 = 5;
pub const PLOSS: u32 = 6;
extern "C" {
    pub static mut signgam: ::core::ffi::c_int;
}
pub const fdversion_fdlibm_ieee: fdversion = -1;
pub const fdversion_fdlibm_svid: fdversion = 0;
pub const fdversion_fdlibm_xopen: fdversion = 1;
pub const fdversion_fdlibm_posix: fdversion = 2;
pub type fdversion = ::core::ffi::c_int;
extern "C" {
    pub static mut _fdlib_version: fdversion;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct exception {
    pub type_: ::core::ffi::c_int,
    pub name: *mut ::core::ffi::c_char,
    pub arg1: ::core::ffi::c_double,
    pub arg2: ::core::ffi::c_double,
    pub retval: ::core::ffi::c_double,
}
extern "C" {
    pub fn racos(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rasin(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn ratan(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn ratan2(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rcos(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rsin(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rtan(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rcosh(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rsinh(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rtanh(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rexp(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn frexp(
        arg1: ::core::ffi::c_double,
        arg2: *mut ::core::ffi::c_int,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn ldexp(arg1: ::core::ffi::c_double, arg2: ::core::ffi::c_int) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rlog(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rlog10(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn modf(
        arg1: ::core::ffi::c_double,
        arg2: *mut ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rpow(arg1: ::core::ffi::c_double, arg2: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rsqrt(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rceil(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rfabs(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rfloor(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rmod(arg1: ::core::ffi::c_double, arg2: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rhypot(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn isnan(arg1: ::core::ffi::c_double) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn finite(arg1: ::core::ffi::c_double) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn atanh(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rcbrt(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn logb(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn nextafter(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rremainder(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn scalb(arg1: ::core::ffi::c_double, arg2: ::core::ffi::c_double)
        -> ::core::ffi::c_double;
}
extern "C" {
    pub fn matherr(arg1: *mut exception) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn significand(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn copysign(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn ilogb(arg1: ::core::ffi::c_double) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn rint(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn scalbn(arg1: ::core::ffi::c_double, arg2: ::core::ffi::c_int) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rexpm1(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn rlog1p(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_sqrt(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_acos(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_log(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_atanh(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_asin(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_atan2(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_exp(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_cosh(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_fmod(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_pow(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_log10(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_sinh(arg1: ::core::ffi::c_double) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_hypot(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_remainder(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__ieee754_rem_pio2(
        arg1: ::core::ffi::c_double,
        arg2: *mut ::core::ffi::c_double,
    ) -> ::core::ffi::c_int;
}
extern "C" {
    pub fn __r__ieee754_scalb(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__kernel_standard(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__kernel_sin(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__kernel_cos(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__kernel_tan(
        arg1: ::core::ffi::c_double,
        arg2: ::core::ffi::c_double,
        arg3: ::core::ffi::c_int,
    ) -> ::core::ffi::c_double;
}
extern "C" {
    pub fn __r__kernel_rem_pio2(
        arg1: *mut ::core::ffi::c_double,
        arg2: *mut ::core::ffi::c_double,
        arg3: ::core::ffi::c_int,
        arg4: ::core::ffi::c_int,
        arg5: ::core::ffi::c_int,
        arg6: *const ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
